In [71]:
import numpy as np


In [72]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [73]:
type(arr)

numpy.ndarray

# 2d array

In [74]:
arr

array([1, 2, 3, 4, 5])

In [75]:
list1=[5,2,1]
list2=[6,7,8]
list3=[11,12,13]
arr=np.array([list1,list2,list3])

In [76]:
arr

array([[ 5,  2,  1],
       [ 6,  7,  8],
       [11, 12, 13]])

# shape and reshape

In [77]:
arr.shape

(3, 3)

In [81]:
arr.reshape(3,3)

array([[ 5,  2,  1],
       [ 6,  7,  8],
       [11, 12, 13]])

In [82]:
arr.ravel() # 2 d arrray to 1d array

array([ 5,  2,  1,  6,  7,  8, 11, 12, 13])

# indexing

In [83]:
#2 d aarray indexing 

In [84]:
arr[:,:]

array([[ 5,  2,  1],
       [ 6,  7,  8],
       [11, 12, 13]])

In [85]:
arr[0:2,:]#slicing

array([[5, 2, 1],
       [6, 7, 8]])

In [86]:
arr[:,0:2]

array([[ 5,  2],
       [ 6,  7],
       [11, 12]])

In [87]:
arr[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [88]:
arr[1:,2:4]

array([[ 8],
       [13]])

In [89]:
arr[1:,3:]

array([], shape=(2, 0), dtype=int32)

In [90]:
arr.size # size of array

9

In [91]:
arr.dtype

dtype('int32')

# dtype= object

In [92]:
np.array({23,34,56})

array({56, 34, 23}, dtype=object)

# 1 d array index

In [93]:
arr1=[1,3,4,6,5,4,3] #one dimentional arrray indexing

In [94]:
arr1[6]

3

# arange function

In [95]:
new=np.arange(15)
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
#when we reshape this arr
new=np.arange(15).reshape(3,5)
new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [97]:
new1=np.arange(0,15,step=2)#start,stop step
new1

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# linspace

In [98]:
np.linspace(1,5,8) 
# start stop, element=how many element you want

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

# zeros and ones

In [99]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
zeros.dtype

dtype('float64')

In [101]:
ones=np.ones((4,2))

In [102]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [103]:
ones.dtype

dtype('float64')

# empty

In [104]:
emp=np.empty((4,5)) #give a empty array with random number
emp

array([[ 0.00000000e+000,  5.02034658e+175,  1.44098993e+160,
         2.44997042e-056,  6.16948261e-062],
       [ 7.96694220e-042,  1.47763641e+248,  1.16096346e-028,
         7.69165785e+218,  1.35617292e+248],
       [ 1.45605741e+185, -2.90028695e-310,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000]])

In [105]:
emp_like=np.empty_like(new1) #empty likecopy the
              # size the other array (new1 is other array)

In [106]:
emp_like

array([        97,        114,        114,         49,         91,
               54,         93, 1530753893])

# identity


In [107]:
ide=np.identity(10)# give 10*10 array
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [108]:
ide.shape

(10, 10)

 # axis

In [109]:
arr

array([[ 5,  2,  1],
       [ 6,  7,  8],
       [11, 12, 13]])

In [110]:
arr.sum(axis=0)

array([22, 21, 22])

In [111]:
arr.sum(axis=1)

array([ 8, 21, 36])

In [112]:
arr.T # t transport the array

array([[ 5,  6, 11],
       [ 2,  7, 12],
       [ 1,  8, 13]])

In [113]:
arr.flat # it show the  itreater

In [114]:
for item in arr.flat: #it print orignal array
    print(item)

5
2
1
6
7
8
11
12
13


In [115]:
arr.ndim # number of dimantion

2

In [116]:
arr.nbytes # totle consuming bytes

36

In [117]:
one=np.array([1,3,5,66,3])

In [118]:
one.argmax() # it give max value index

3

In [119]:
one.argmin() # it give min value index 

0

In [120]:
one.argsort() # sort indext with respact increasing order

array([0, 1, 4, 2, 3], dtype=int64)

In [121]:
# in the same two d array=it srot the 
#and then check indext
arr

array([[ 5,  2,  1],
       [ 6,  7,  8],
       [11, 12, 13]])

In [122]:
arr.argmin() #( arg function give index of the value)

2

In [123]:
arr.argmax()

8

In [124]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [125]:
arr.argmax(axis=1)

array([0, 2, 2], dtype=int64)

In [126]:
arr.argsort(axis=1)

array([[2, 1, 0],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [127]:
 arr2=np.array([[1,3,4],[1,4,2],[2,3,4]])
    

In [128]:
arr2

array([[1, 3, 4],
       [1, 4, 2],
       [2, 3, 4]])

In [129]:
arr

array([[ 5,  2,  1],
       [ 6,  7,  8],
       [11, 12, 13]])

In [130]:
arr+arr2 #sum of two array

array([[ 6,  5,  5],
       [ 7, 11, 10],
       [13, 15, 17]])

In [131]:
arr*arr2 #multiply

array([[ 5,  6,  4],
       [ 6, 28, 16],
       [22, 36, 52]])

In [132]:
np.sqrt(arr2) #squer

array([[1.        , 1.73205081, 2.        ],
       [1.        , 2.        , 1.41421356],
       [1.41421356, 1.73205081, 2.        ]])

In [133]:
arr2.sum()

24

In [140]:
arr3=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [141]:
np.where(arr3>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [142]:
np.count_nonzero(arr3)

8

# copy and brodcasting

In [149]:
ar=np.array([2,3,5,6,74,2,4,4])

In [150]:
ar[3:]=100 #brodcasting
ar

array([  2,   3,   5, 100, 100, 100, 100, 100])

In [156]:
ar11=ar#copy value

In [157]:
ar11[3:]=500
ar11

array([  2,   3,   5, 500, 500, 500, 500, 500])

In [158]:
ar #the orginal value are change its means the array is
   #refernce type

array([  2,   3,   5, 500, 500, 500, 500, 500])

In [160]:
ar<3 

array([ True, False, False, False, False, False, False, False])

In [162]:
#when we want to see those actule value not see true false
ar[ar>5]

array([500, 500, 500, 500, 500])

# random 

In [163]:
 np.random.rand(3,3) 

array([[0.12384384, 0.5948597 , 0.76092984],
       [0.71660201, 0.28493805, 0.71506242],
       [0.91083507, 0.38686204, 0.37575912]])

In [164]:
np.random.randn(4,4)

array([[-0.33764659,  0.80877618, -0.29584506,  0.08058669],
       [ 0.00606082, -0.02248489,  0.12801034, -0.12914677],
       [-0.98969481, -0.81801288, -1.06157291, -0.82801309],
       [-0.79023804,  0.70286658, -1.5453437 ,  0.57967223]])

In [165]:
np.random.randint(0,1000,(4,4)) #number are change 
                #  again and again when we excute the code 

array([[281, 312, 540, 380],
       [ 96, 726, 185, 476],
       [551, 494, 406, 176],
       [ 31, 780, 830, 622]])

In [174]:
np.random.randint(1,1000,6).reshape(3,2)

array([[137, 372],
       [926, 884],
       [ 60, 419]])

In [169]:
#how to constant random number value
a1=np.random.seed(101)
a1=np.random.randint(0,100,10) #its value are fix allways
a1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [172]:
a1.mean() #average

60.8

In [177]:
np.std(a1)

29.006206232459977